source 'https://github.com/CocoaPods/Specs.git'
source 'git@github.com:bistri/mobile_sdk.git'

platform :ios, '12.4'

target 'api_demo' do
  use_frameworks!

  # Pods for api_demo
  pod 'bistriSDK'

end
