source 'https://github.com/CocoaPods/Specs.git'
source 'git@github.com:bistri/mobile_sdk.git'

platform :ios, '16.2'

target 'api_demo' do
  use_frameworks!

  # Pods for api_demo
  pod 'bistriSDK'

end

post_install do |installer|
	installer.pods_project.targets.each do |target|
		target.build_configurations.each do |config|
			config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
		end
	end
end

